/**
 * AUTO-GENERATED from assets/game/battle-views — bundled RISK II battle
 * backdrops, one aerial painting per territory, keyed by territory id.
 */
export const BATTLE_VIEW_SOURCES: Record<string, number> = {
  afghanistan: require('../assets/game/battle-views/afghanistan.webp'),
  alaska: require('../assets/game/battle-views/alaska.webp'),
  alberta: require('../assets/game/battle-views/alberta.webp'),
  argentina: require('../assets/game/battle-views/argentina.webp'),
  brazil: require('../assets/game/battle-views/brazil.webp'),
  centralAmerica: require('../assets/game/battle-views/centralAmerica.webp'),
  china: require('../assets/game/battle-views/china.webp'),
  congo: require('../assets/game/battle-views/congo.webp'),
  eastAfrica: require('../assets/game/battle-views/eastAfrica.webp'),
  easternAustralia: require('../assets/game/battle-views/easternAustralia.webp'),
  easternUS: require('../assets/game/battle-views/easternUS.webp'),
  egypt: require('../assets/game/battle-views/egypt.webp'),
  falklandIslands: require('../assets/game/battle-views/falklandIslands.webp'),
  greatBritain: require('../assets/game/battle-views/greatBritain.webp'),
  greenland: require('../assets/game/battle-views/greenland.webp'),
  hawaii: require('../assets/game/battle-views/hawaii.webp'),
  iceland: require('../assets/game/battle-views/iceland.webp'),
  india: require('../assets/game/battle-views/india.webp'),
  indonesia: require('../assets/game/battle-views/indonesia.webp'),
  irkutsk: require('../assets/game/battle-views/irkutsk.webp'),
  japan: require('../assets/game/battle-views/japan.webp'),
  kamchatka: require('../assets/game/battle-views/kamchatka.webp'),
  madagascar: require('../assets/game/battle-views/madagascar.webp'),
  middleEast: require('../assets/game/battle-views/middleEast.webp'),
  mongolia: require('../assets/game/battle-views/mongolia.webp'),
  newGuinea: require('../assets/game/battle-views/newGuinea.webp'),
  newZealand: require('../assets/game/battle-views/newZealand.webp'),
  northAfrica: require('../assets/game/battle-views/northAfrica.webp'),
  northernEurope: require('../assets/game/battle-views/northernEurope.webp'),
  northwestTerritory: require('../assets/game/battle-views/northwestTerritory.webp'),
  ontario: require('../assets/game/battle-views/ontario.webp'),
  peru: require('../assets/game/battle-views/peru.webp'),
  philippines: require('../assets/game/battle-views/philippines.webp'),
  quebec: require('../assets/game/battle-views/quebec.webp'),
  scandinavia: require('../assets/game/battle-views/scandinavia.webp'),
  siam: require('../assets/game/battle-views/siam.webp'),
  siberia: require('../assets/game/battle-views/siberia.webp'),
  southAfrica: require('../assets/game/battle-views/southAfrica.webp'),
  southernEurope: require('../assets/game/battle-views/southernEurope.webp'),
  svalbard: require('../assets/game/battle-views/svalbard.webp'),
  ukraine: require('../assets/game/battle-views/ukraine.webp'),
  ural: require('../assets/game/battle-views/ural.webp'),
  venezuela: require('../assets/game/battle-views/venezuela.webp'),
  westAfrica: require('../assets/game/battle-views/westAfrica.webp'),
  westernAustralia: require('../assets/game/battle-views/westernAustralia.webp'),
  westernEurope: require('../assets/game/battle-views/westernEurope.webp'),
  westernUS: require('../assets/game/battle-views/westernUS.webp'),
  yakutsk: require('../assets/game/battle-views/yakutsk.webp'),
};
