// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/battle-screen/FaithfulClassic.tsx": () => import("../components/mockups/battle-screen/FaithfulClassic.tsx"),
  "./components/mockups/battle-screen/ParchmentTheatre.tsx": () => import("../components/mockups/battle-screen/ParchmentTheatre.tsx")
};
