import { Storage } from '@google-cloud/storage';
const SIDECAR = 'http://127.0.0.1:1106';
const storage = new Storage({ credentials: { audience:'replit', subject_token_type:'access_token', token_url:`${SIDECAR}/token`, type:'external_account', credential_source:{ url:`${SIDECAR}/credential`, format:{type:'json',subject_token_field_name:'access_token'} }, universe_domain:'googleapis.com' }, projectId:'' });
const sp = (process.env.PUBLIC_OBJECT_SEARCH_PATHS||'').split(',')[0].trim();
const parts = sp.replace(/^\//,'').split('/');
const bucket = parts[0], prefix = parts.slice(1).join('/');
const [files] = await storage.bucket(bucket).getFiles({ prefix });
const rel = files.map(f=>f.name.slice(prefix.length?prefix.length+1:0)).sort();
console.log('SFX present:', rel.filter(r=>r.startsWith('public/risk/sfx/')).map(r=>r.split('/').pop()).join(' '));
console.log('DICE:', rel.filter(r=>r.startsWith('public/risk/dice/')).length, 'FIREWORKS:', rel.filter(r=>r.startsWith('public/risk/fireworks/')).length, 'BATTLE-VIEWS:', rel.filter(r=>r.startsWith('public/battle-views/')).length);
console.log('other public/risk files:', rel.filter(r=>r.startsWith('public/risk/')&&!/\/(sfx|dice|fireworks)\//.test(r)).join(', ')||'(none)');
console.log('legacy risk/ sample:', rel.filter(r=>r.startsWith('risk/')).slice(0,8).join(', '), '... total', rel.filter(r=>r.startsWith('risk/')).length);
console.log('legacy top-level:', rel.filter(r=>!r.startsWith('public/')&&!r.startsWith('risk/')).join(', '));
